import { ComingSoonPanel, ContentSection, FeatureGrid, FeatureItem, PageHero } from "@/components/common/PublicPage";
import { Layout } from "@/components/layout/Layout";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Partner with us", description: "Healthcare, community, corporate, funding and technical partnership opportunities with Hope4PKD.", alternates: { canonical: "/partner" } };

export default function PartnerPage() {
  return <Layout><PageHero eyebrow="Partner with us" title="Partner with Hope4PKD on care, funding and operations." description="Hope4PKD is seeking healthcare, community, funding and technical partners that can work with clear roles, patient dignity and public accountability." /><ContentSection><FeatureGrid columns={3}><FeatureItem title="Healthcare providers">Referral pathways, verification, diagnostics, treatment and responsible continuity of care.</FeatureItem><FeatureItem title="Patient & community groups">Trusted education, caregiver support, listening and community connection.</FeatureItem><FeatureItem title="Corporate & institutional funders">Restricted or general support with defined reporting and no inappropriate patient access.</FeatureItem><FeatureItem title="Professional bodies">Medical review, clinical governance and evidence-led public education.</FeatureItem><FeatureItem title="Technology & operations">Privacy, security, accessible service delivery and resilient programme infrastructure.</FeatureItem><FeatureItem title="Research & policy">Ethical aggregate learning and advocacy without repurposing patient data.</FeatureItem></FeatureGrid><ComingSoonPanel title="The partnership form is not open yet" description="The form will open after routing, acknowledgement, spam protection and data-handling approvals are operational. Partner names and logos will appear only after verification and permission." /></ContentSection></Layout>;
}
