import { ContentSection, EmptyState, FeatureGrid, FeatureItem, PageHero, SectionHeading } from "@/components/common/PublicPage";
import { Layout } from "@/components/layout/Layout";
import { Grid, Heading, Text, VStack } from "@chakra-ui/react";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Impact & transparency", description: "How Hope4PKD separates verified results from targets, controls case publication, and plans financial reporting.", alternates: { canonical: "/impact" } };

export default function ImpactPage() {
  return <Layout><PageHero eyebrow="Impact & transparency" title="Trust is a record of what happened—not a promise." description="Hope4PKD will publish evidence, reporting periods, definitions and approvals beside every programme or financial figure." /><ContentSection><Grid templateColumns={{ base: "1fr", lg: "1fr 1fr" }} gap={6}><VStack align="start" bg="navy.900" color="white" borderRadius="2xl" p={8}><Text color="brightTeal.500" fontWeight="800">Verified results</Text><Heading as="h2" color="white" fontSize="4xl">Pilot reporting state</Heading><Text color="navy.100" lineHeight="1.7">No programme totals have been approved for publication. Results will appear only with a reporting period, methodology and responsible owner.</Text></VStack><VStack align="start" bg="pink.50" borderWidth="1px" borderColor="pink.200" borderRadius="2xl" p={8}><Text color="pink.700" fontWeight="800">Year-one target</Text><Heading as="h2" fontSize="4xl">Build accountable operations</Heading><Text color="navy.600" lineHeight="1.7">Launch reviewed intake, case controls, verified campaign publishing, allocation records and the first sourced programme report.</Text></VStack></Grid></ContentSection><ContentSection tone="teal"><SectionHeading eyebrow="Control framework" title="How support and funding will be governed." /><FeatureGrid columns={3}><FeatureItem title="Case verification">Medical and programme roles review different parts of a case with least-privilege access.</FeatureItem><FeatureItem title="Public projection">Campaign pages use an approved public record, never raw medical or case tables.</FeatureItem><FeatureItem title="Financial separation">Donations, fees, allocations, disbursements, refunds and subscription state are recorded separately.</FeatureItem><FeatureItem title="Consent history">The identity level, story approval and consent version are retained for each publication.</FeatureItem><FeatureItem title="Audit trail">Sensitive actions generate append-only events with actor, reason and time.</FeatureItem><FeatureItem title="Policy gates">Donations, refunds, campaign surplus and reporting stay off until approved policies exist.</FeatureItem></FeatureGrid></ContentSection><ContentSection><SectionHeading eyebrow="Reports & governance" title="The evidence library will grow with the programme." /><EmptyState title="No approved public reports yet" description="Registration details, governance records, audited or independently reviewed financial reports, impact data and confirmed partners will be linked here after approval. Empty categories are not padded with provisional material." actionLabel="Read our policy suite" actionHref="/policies/privacy" /></ContentSection></Layout>;
}
