import { ContentSection, EmptyState, FeatureGrid, FeatureItem, PageHero, SectionHeading } from "@/components/common/PublicPage";
import { Layout } from "@/components/layout/Layout";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "PKD Knowledge Centre", description: "A medically reviewed, dated, referenced and accessible PKD information centre in development.", alternates: { canonical: "/knowledge" } };

export default function KnowledgePage() {
  return <Layout><PageHero eyebrow="PKD Knowledge Centre" title="Clear information, with medical review you can verify." description="Articles will show authorship, reviewer qualifications, references, publication and review dates, a disclaimer and the next review date." /><ContentSection><SectionHeading eyebrow="Planned collections" title="Information for each point in the journey." /><FeatureGrid columns={3}><FeatureItem title="Understanding PKD">Foundational information about inherited cystic kidney disease and questions to discuss with a clinician.</FeatureItem><FeatureItem title="Diagnosis & monitoring">Responsible explanations of tests, appointments and monitoring without replacing clinical advice.</FeatureItem><FeatureItem title="Living with PKD">Practical, reviewed guidance for patients, caregivers and families.</FeatureItem><FeatureItem title="Treatment pathways">Plain-language orientation to care pathways, dialysis and transplantation.</FeatureItem><FeatureItem title="Caregiving">Support for the people coordinating care, appointments and family communication.</FeatureItem><FeatureItem title="Rights & support">Information about consent, privacy, support processes and responsible fundraising.</FeatureItem></FeatureGrid><EmptyState title="Medical review is being established" description="No article is labelled medically reviewed until a qualified reviewer account, independence rule, references and next-review date are complete. For personal medical advice, speak with a qualified healthcare professional." actionLabel="Read the medical disclaimer" actionHref="/medical-disclaimer" /></ContentSection></Layout>;
}
