import { ComingSoonPanel, ContentSection, FeatureGrid, FeatureItem, PageHero } from "@/components/common/PublicPage";
import { Layout } from "@/components/layout/Layout";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Donate", description: "Online donations will open after Hope4PKD approves payment, finance, fee, refund, surplus and settlement controls.", alternates: { canonical: "/donate" } };

export default function DonatePage() {
  return <Layout><PageHero eyebrow="Donate" title="Track every donation from payment to allocation." description="Online donations will use Paystack-hosted checkout, provider confirmation, receipts and separate allocation records. Hope4PKD will not handle card data." /><ContentSection><FeatureGrid columns={3}><FeatureItem title="Secure start">The Hope4PKD service will start each payment before sending the donor to checkout.</FeatureItem><FeatureItem title="Provider confirmation">Paystack must confirm a payment before Hope4PKD records it as successful.</FeatureItem><FeatureItem title="Traceable allocations">Approved general-fund and campaign allocations remain traceable.</FeatureItem><FeatureItem title="No card storage">Card details stay with the regulated payment provider.</FeatureItem><FeatureItem title="Donation receipt">Hope4PKD will send one acknowledgement and receipt for each confirmed donation.</FeatureItem><FeatureItem title="Approved policies">Fees, refunds, subscriptions and campaign surplus follow approved rules.</FeatureItem></FeatureGrid><ComingSoonPanel title="Online donations are not active yet" description="Hope4PKD is confirming its live Paystack account, settlement details, fee treatment, finance owner, refund policy and campaign-surplus policy. Bank details and checkout will appear only after approval." /></ContentSection></Layout>;
}
